blueprint:
  name: Chauffage intelligent - 🛎️ Notifier Température anormale (v2)
  domain: automation
  author: JLo
  input:
    room_name:
      name: Room name
      description: Room name you want to monitor
      selector:
        text:
    room_temperature:
      name: Room temperature
      description: Room temperature you want to monitor
      selector:
        entity:
          filter:
            device_class: temperature
    room_openings:
      name: Room openings
      description: Room openings you want to monitor
      selector:
        entity:
          multiple: true
          filter:
            device_class:
              - opening
              - door
              - window
    room_openings_duration:
      name: Room openings duration
      description: how long the room openings need to be left open for the automation to trigger
      selector:
        time:
    outside_temperature:
      name: Outside temperature
      selector:
        entity:
          filter:
            device_class: temperature
    power_notification_script:
      name: Power notification Script
      description: Script to use to send the abnormal temperature notification
      selector:
        entity:
          filter:
            domain: script

triggers:
  - trigger: state
    entity_id: !input room_temperature
  - trigger: state
    entity_id: !input room_openings
    to: "on"
    for: !input room_openings_duration
  - trigger: state
    entity_id: !input room_openings
    to: "off"
  - trigger: state
    entity_id: !input outside_temperature
  - trigger: state
    entity_id: input_number.interior_temperature_max_acceptable
  - trigger: state
    entity_id: input_number.interior_temperature_min_acceptable
  - trigger: state
    entity_id: input_boolean.automation_heat_home
  - trigger: homeassistant
    event: start
    id: restart
conditions:
  - condition: state
    entity_id: input_boolean.automation_heat_home
    state: "on"
actions:
  - variables:
      room_name_variable: !input room_name
      room_temp: !input room_temperature
      outside_temp: !input outside_temperature
  - choose:
      - conditions:
          - condition: state
            entity_id: !input room_openings
            state: "on"
          - condition: numeric_state
            entity_id: !input room_temperature
            below: input_number.interior_temperature_min_acceptable
          - condition: numeric_state
            entity_id: !input outside_temperature
            below: input_number.interior_temperature_min_acceptable
          - condition: numeric_state
            entity_id: !input outside_temperature
            below: !input room_temperature
        sequence:
          - action: script.turn_on
            target:
              entity_id: !input power_notification_script
            data:
              variables:
                user_title: ❄️ Perte de température
                user_message: >-
                  {{room_name_variable}} refroidit ({{states(room_temp, with_unit=True)}}) car des fenêtres sont ouvertes il qu'il fait
                  froid dehors ({{states(outside_temp, with_unit=True)}})
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
      - conditions:
          - condition: state
            entity_id: !input room_openings
            state: "on"
          - condition: numeric_state
            entity_id: !input room_temperature
            above: input_number.interior_temperature_max_acceptable
          - condition: numeric_state
            entity_id: !input outside_temperature
            above: input_number.interior_temperature_max_acceptable
          - condition: numeric_state
            entity_id: !input outside_temperature
            above: !input room_temperature
        sequence:
          - action: script.turn_on
            target:
              entity_id: !input power_notification_script
            data:
              variables:
                user_title: 🌡️ Gain de température
                user_message: >-
                  {{room_name_variable}} chauffe ({{states(room_temp, with_unit=True)}}) car des fenêtres sont ouvertes il qu'il fait
                  chaud dehors ({{states(outside_temp, with_unit=True)}})
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
mode: single
max_exceeded: silent
