# Default sensors and inputs for all ESPHome configurations

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: uptime
    id: Uptime

# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: Restart
