homeassistant:
  customize:
    sensor.jean_loics_laptop_internal_battery_level:
      ignore_battery: true
    sensor.quest_battery_level:
      ignore_battery: true
    sensor.iphone_de_valentine_battery_level:
      ignore_battery: true
    sensor.jean_loics_iphone_battery_level:
      ignore_battery: true
    sensor.neuneu_battery_level:
      ignore_battery: true
