input_boolean:
  vacuum_zone_living_room:
    icon: mdi:sofa
    name: Aspirateur Zone Salon
  vacuum_zone_kitchen:
    icon: mdi:fridge
    name: Aspirateur Zone Cuisine
  vacuum_zone_entry:
    icon: mdi:coat-rack
    name: Aspirateur Zone Entrée
  vacuum_zone_celar:
    icon: mdi:archive
    name: Aspirateur Zone Cellier
  vacuum_zone_bathroom:
    icon: mdi:bathtub
    name: Aspirateur Zone Salle de bains

homeassistant:
  customize:
    input_boolean.vacuum_zone_living_room:
      vacuum_segment: 4
      vacuum_floor: 0
    input_boolean.vacuum_zone_kitchen:
      vacuum_segment: 3
      vacuum_floor: 0
    input_boolean.vacuum_zone_entry:
      vacuum_segment: 5
      vacuum_floor: 0
    input_boolean.vacuum_zone_celar:
      vacuum_segment: 2
      vacuum_floor: 0
    input_boolean.vacuum_zone_bathroom:
      vacuum_segment: 1
      vacuum_floor: 0

template:
  - sensor:
      - unique_id: "vacuum_first_floor_selected_rooms"
        name: "Pièces sélectionnées (Rez-de-chaussée)"
        icon: mdi:home-floor-0
        unit_of_measurement: "Pièces"
        state: |
          {{ 
            expand(states.input_boolean)  
              | selectattr('attributes.vacuum_floor', 'defined')
              | selectattr('attributes.vacuum_floor', 'eq', 0)
              | selectattr('state', 'eq', 'on')
              | selectattr('attributes.vacuum_segment', 'defined')
              | list 
              | count 
          }}
        attributes:
          room_list: |
            {{ 
              expand(states.input_boolean)  
                | selectattr('attributes.vacuum_floor', 'defined')
                | selectattr('attributes.vacuum_floor', 'eq', 0)
                | selectattr('state', 'eq', 'on')
                | selectattr('attributes.vacuum_segment', 'defined')
                | map(attribute='attributes.vacuum_segment') 
                | list 
                | sort
            }}
